### ISSUE TITLE
compatible with PHP v5.3

### ISSUE THREAD

**Issue by shuge** [mariano/disque-php#23]

**Comment by mariano** [comment]
@shuge what's this issue supposed to be? Are you asking for disque-php to support PHP 5.3?

Unfortunately that's not in my plans. 5.3 has been unsupported for over an year and four months, and building libraries that continue to target that PHP version only favor users utilizing a PHP version that should no longer be used.

I know it might seem like an unpopular decision, but I do think it's for the greater good. Similarly PHP 5.4 has been unsupported for more than 3 months, that's why I only targetted 5.5 as a minimum required version.
